apiVersion: v1
kind: Namespace
metadata:
  name: db-ns

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
  namespace: db-ns
data:
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "flask_app_db"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: db-ns
  labels:
    app: database-deployment
    version: v1
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        version: v1
        env: dev
    spec:
      containers:
        - name: database
          image: postgres:13
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-configmap
      volumes:
        - name: postgres-persistent-storage

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db-ns
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: database