apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: db-ns
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8QPQeRfqyn4rAjG7,iv:oW1qkxB8lwLyNWsPG/XZec6VQbzx+7XFfjAtIt1m7lo=,tag:rKHVEE1anP3s+UQZ4uce5g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/myfirstapp-72240/locations/northamerica-northeast1/keyRings/keyring-01/cryptoKeys/my-key
          created_at: "2024-11-19T16:31:30Z"
          enc: CiQAFDaF8IhH+gjOaCWIHBVF+U898viW799ACoX4/oQMo6+NtaMSSQCVhutkAWLpUy7+FPnKhKq2gS26zLos19QiJ1lwX78vqJcvCx2kDVlZ3SLQT0JlcTdL3yhnBUeVrzVqd4cWWbmcsO6QjdjuXCQ=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T16:31:31Z"
    mac: ENC[AES256_GCM,data:myoAGVgzaTEERCLFlacXkUq3C5yUBHmFjZRVzPxFjYtxW88zYYDHrDt0YPhHugv4BSwpoVfRkvTzOyMGn7Rvi9Ci13NDt3Oku+W29vLkl2rXq4CKlAvSLEykMcPvuiX/ChQK3HpzdquHx2Qbo1T1doPwX8DSGfu9z9lbybTqYb0=,iv:q3gzoAijFAM2PNUCvOidChqutQP80bK8687V9eCuCC8=,tag:qjoCJUp5oT5FGIxYxuM+vQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
